name: Github-actions-example CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: FRONTEND - install and build
        run: |
          cd frontend
          npm i  --force
          npm run build
      - name: BACKEND install
        run: |
          npm i --force
      - name: BACKEND - restart
          pm2 stop 0
          pm2 start 0
          pm2 save
      - name: PROXY - restart
          sudo service nginx restart

